name: data_table_plus
description: In-place replacement for Flutter's DataTable and PaginatedDataTable
version: 0.0.1
homepage: https://github.com/ReniDelonzek/data_table_plus
repository: https://github.com/ReniDelonzek/data_table_plus

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: "^2.1.0"
