name: data_table_plus
description: A table library following the standard Flutter structure with some increments
version: 0.0.2
homepage: https://github.com/ReniDelonzek/data_table_plus
repository: https://github.com/ReniDelonzek/data_table_plus

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: ^2.1.4
